/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MathgnRouteImport } from './routes/mathgn'
import { Route as IndexRouteImport } from './routes/index'

const MathgnRoute = MathgnRouteImport.update({
  id: '/mathgn',
  path: '/mathgn',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mathgn': typeof MathgnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mathgn': typeof MathgnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mathgn': typeof MathgnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/mathgn'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mathgn'
  id: '__root__' | '/' | '/mathgn'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MathgnRoute: typeof MathgnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mathgn': {
      id: '/mathgn'
      path: '/mathgn'
      fullPath: '/mathgn'
      preLoaderRoute: typeof MathgnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MathgnRoute: MathgnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
